#!/bin/bash

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

protected_branch_pattern='^(refs/heads/)?(master|main)$'

while read -r local_ref local_sha remote_ref remote_sha
do
  if [[ $remote_ref =~ $protected_branch_pattern ]]; then
    if [[ "$ALLOW_PROTECTED_PUSH" != "1" ]]; then
      printf "${RED}Push blocked.${NC}\n"
      printf "Refusing to push to ${YELLOW}%s${NC}.\n" "$remote_ref"
      printf "If this is intentional, rerun with ${YELLOW}ALLOW_PROTECTED_PUSH=1 git push ...${NC}\n"
      exit 1
    fi

    printf "${YELLOW}Warning:${NC} pushing to protected branch %s with override enabled.\n" "$remote_ref"
  fi
done

# Function to output result of tests
output_result() {
  ret_code=$1
  message=$2
  output=$3

  if [ $ret_code != 0 ]; then
    printf "${RED}${message} failed.${NC}\n"
    echo "$output"
    pass=false
  else
    printf "${GREEN}$message passed.${NC}\n"
  fi
}

# Get number of uncommitted changes
CHANGES=$(git diff --numstat | wc -l)
CHANGES_CACHED=$(git diff --cached --numstat | wc -l)
TOTAL_CHANGES=$(($CHANGES + $CHANGES_CACHED))

# Stash all uncommitted changes before running tests
git stash -k

run_lint() {
  local dir=$1

  cd $dir
  tslint=$(npm run lint)
}

echo "Running planet linters"
run_lint .

ret_code_tslint=$?
output_result $ret_code_tslint "eslint" $tslint

echo "Running gateway linters"
run_lint gateway

ret_code_tslint=$?
output_result $ret_code_tslint "tslint" $tslint

# If we stashed changes earlier, pop them back off the stack
if [ $TOTAL_CHANGES -ne "0" ]
then
  echo "Popping" $TOTAL_CHANGES "changes off the stack..."
  git stash pop -q
fi

# The 0 exit code will only be sent if pass=true
# Any failure will set pass=false
if $pass; then
  exit 0
fi

exit 1
