services:
  couchdb:
    expose:
      - 5984
    image: treehouses/couchdb:2.3.1
    ports:
      - "2400:5984"
  db-init:
    image: treehouses/planet:db-init-local
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: treehouses/planet:local
    ports:
      - "3200:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - MULTIPLE_IPS=true
      - HOST_PROTOCOL=http
      - DB_HOST=127.0.0.1
      - DB_PORT=2200
      - CENTER_ADDRESS=planet.earth.ole.org/db
    depends_on:
      - couchdb
