export const conditions = [
  'Cancer',
  'Cardiovascular disorders',
  'Cirrhosis of the liver',
  'Diabetes',
  'Diarrhoea diseases',
  'Ebola',
  'Epilepsy',
  'FGM',
  'Influenza',
  'Ischaemic heat disease',
  'Malaria',
  'Malnutrition',
  'Meningitis',
  'Neonatal sepsis and infections',
  'HIV/AIDS',
  'Pneumonia',
  'Stroke',
  'Tuberculosis',
];
