export const conditions = [
  $localize`Acute Otitis Media`,
  $localize`Acute Respiratory Infection`,
  $localize`Amebiasis`,
  $localize`Brucellosis`,
  $localize`Cancer`,
  $localize`Cardiovascular disorders`,
  $localize`Chagas Disease`,
  $localize`Chancroid`,
  $localize`Chikungunya`,
  $localize`Chlamydia`,
  $localize`Chronic Kidney Disease`,
  $localize`Cirrhosis of the liver`,
  $localize`Conjunctivitis`,
  $localize`COVID-19`,
  $localize`Cryptosporidiosis`,
  $localize`Dental Caries`,
  $localize`Dengue`,
  $localize`Diabetes`,
  $localize`Diarrhoea diseases`,
  $localize`Ebola`,
  $localize`Emphysema`,
  $localize`Epilepsy`,
  $localize`FGM`,
  $localize`Fungal Infection`,
  $localize`Giardiasis`,
  $localize`Gonorrhea`,
  $localize`Heatstroke`,
  $localize`Hepatitis A`,
  $localize`Hepatitis B`,
  $localize`Hepatitis C`,
  $localize`Herpes Simplex Virus`,
  $localize`HIV/AIDS`,
  $localize`Human Papillomavirus`,
  $localize`Hypertension`,
  $localize`Influenza`,
  $localize`Iron-Deficiency Anemia`,
  $localize`Ischaemic heart disease`,
  $localize`Iodine Deficiency`,
  $localize`Leishmaniasis`,
  $localize`Leptospirosis`,
  $localize`Low Birth Weight`,
  $localize`Lymphogranuloma Venereum`,
  $localize`Malaria`,
  $localize`Malnutrition`,
  $localize`Maternal Hemorrhage`,
  $localize`Measles`,
  $localize`Meningitis`,
  $localize`Mycoplasma genitalium`,
  $localize`Neonatal sepsis and infections`,
  $localize`Obesity`,
  $localize`Pneumonia`,
  $localize`Preeclampsia/Eclampsia`,
  $localize`Preterm Birth Complications`,
  $localize`Rabies`,
  $localize`Rotavirus`,
  $localize`Scabies`,
  $localize`Schistosomiasis`,
  $localize`Soil-Transmitted Helminths`,
  $localize`Stroke`,
  $localize`Syphilis`,
  $localize`Trauma`,
  $localize`Trichomoniasis`,
  $localize`Tuberculosis`,
  $localize`Typhoid Fever`,
  $localize`Vitamin A Deficiency`,
  $localize`Zika`
];

export const conditionAndTreatmentFields = [
  'notes', 'diagnosis', 'treatments', 'medications', 'immunizations', 'allergies', 'xrays', 'tests', 'referrals'
];

export const vitals = [
  'temperature',
  'pulse',
  'bp',
  'height',
  'weight',
  'vision',
  'hearing'
];
