name: Pre-Planet Builder

on: workflow_dispatch

jobs:
  build:
    name: Pre-Planet build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}

      - name: Build image
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          repo="rjpadilla/preplanet:latest"
          mkdir -p ./ng-app/dist
          docker build -f './docker/planet/pre-builder-Dockerfile' -t $repo . 
          docker images
          docker push $repo